### ISSUE TITLE
cannot umount or mount an sshfs volume after ssh connection cut

### ISSUE THREAD

**Issue by kcleung** [macfuse/macfuse#45] opened 2012-08-04 08:50 UTC
I am using OS X 10.8 with osxfuse 2.5 and sshfs 2.4.1.  After an sshfs volume is disrupted by the remote ssh tunnel server cutting the connection, I can't unmount the directory:

$ umount dir
umount: dir: not currently mounted

$ls dir
ls: dir: Input/output error

But I can't remount the volume to the directory again:

$sshfs user@server:/dir dir
fuse: bad mount point `dir': Input/output error

Is this the problem of sshfs, or osxfuse?

**Comment by tejeswinisundaram** [comment] 2015-02-23 09:24
I had a similiar problem in Linux Ubuntu 14.04. I followed the instruction of killing the sshfs process. and then ran a fuser -u path/to/mount/directory. It solved the issue.

But, what is the safe way to fix this problem ?

**Comment by bachinskiyv** [comment] 2015-02-24 14:35
Thank you, @gtournie

**Comment by jklein** [comment] 2015-03-30 21:37
Same issue here, @gtournie's solution worked for me :+1:

**Comment by jadik** [comment] 2015-05-09 09:43
Many thanks, @gtournie ... the force option proved worthy!

**Comment by mmocny** [comment] 2015-05-14 14:20
Kept running into this, realized it was because I had open files (MacVim in this case) from the now-defunct mount point.  Once I closed the files, I could do a simple umount.

**Comment by bearfriend** [comment] 2015-05-19 17:13
I had this issue, and was able to `force` unmount the drive. I then got it to mount properly by disconnecting from a VPN I was on, and NOT using `sudo`.

```
mkdir ~/Volumes && mkdir $_/my-new-drive
sshfs ... ~/Volumes/my-new-drive/
```

**Comment by MicrMc** [comment] 2015-06-01 17:30
I have tried all of these work arounds to unmount my folder however none are working. I am told that unmount command is not found and pgrep will show me this:

36542 s001  S+     0:00.00 grep sshfs

However I cannot do anything with it in terms of killing it. 
I am using OSXFUSE 2.7.5 on OSX Yosemite. Is there something else that I can do to unmount this folder?

**Comment by ajcf** [comment] 2015-06-01 22:34
@MicrMac, apologies if this is wrong, but I see that you wrote "the unmount command is not found". The command is "umount" - I aslo run Yosemite and usually I run "umount -f remote.host:/mounted/path"

**Comment by phucng** [comment] 2015-06-07 06:02
Thanks @gtournie! At least we have a way around.

**Comment by leipzig** [comment] 2015-06-25 15:28
@gtournie's solution must be a full path

**Comment by HollyZB** [comment] 2015-07-29 16:25
solution provided by @theunsa worked for me; thanks!

**Comment by viniciusgomes** [comment] 2015-08-04 14:42
Guys another solution

$ diskutil unmount "[full-path-from-root]"

**Comment by iromeo** [comment] 2015-08-12 16:12
@viniciusgomes thanks, work for me

**Comment by jatinchuglani** [comment] 2015-09-16 06:52
For me the above 'umount -f "[full-path-from-root]"', but "umount -A" worked, clearing all the stale mounts.
This is not the ideal approach as it unmounts all the mounted drives, but that is the only thing that worked for me.

**Comment by MicrMc** [comment] 2015-09-16 07:55
Thanks, umount -f has worked brilliantly for me.

Thanks for the help


________________________________

**Comment by jhihn** [comment] 2015-10-09 20:17
The force unmount does not always work.  Not usually in fact.  
I have tried :
sudo umount - f /mountpoint
sudo launchctl stop com.apple.autofsd
sudo diskutil unmount force /mountpoint

It seems that when  it dies,  any of those commands may succeed or hang forever.

**Comment by ravizombie** [comment] 2015-10-19 18:37
After trying to kill sshfs, though the process was killed,
Umount still didnt work, and I couldnt mount at the same point.

Then, I tried with 

    sudo diskutil umount force [path]
didnt work for me
Hence I tried hdituil, it worked.
     hdiutil eject -force <full mount path>

**Comment by toolforger** [comment] 2015-11-14 10:35
I'm getting stuck `sync` processes that I can't even `kill -9`.
Rebooting waits for these, so I'm forced to do hardware resets.

Environment: Linux 3.13.0-68-generic #111-Ubuntu SMP x86_64

I also keep getting read/write errors from `update-grub` on the disk. What happens is that `grub-update` finds an Ubuntu installation (there's a full-system backup on that machine, the detection is probably being served from disk cache), tries to write the boot loader as it is supposed to do, but gets IO errors (I suspect that's because the remote end of the SSH connection is closed down by timeout or something).
I'm seeing there's a ton of debugging options on sshfs, but I have no idea which of these is going to return useful log messages.

**Comment by dzhwinter** [comment] 2016-01-06 07:37
+1 
os mac 10.11
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.2

when I open a large repo in server, sshfs daemon process will be stuck.

**Comment by snadrus** [comment] 2016-02-17 23:40
A simpler solution 2:
pkill -9 sshfs && umount <mountpoint>

**Comment by evisong** [comment] 2016-05-05 06:19
In my case, osxfuse/macfusion cannot resume after Mac wake up from a sleep, moreover I always fail to re-mount unless I reboot the Mac. 

    hdiutil eject -force <full mount path>

This solution works for me, I can re-mount after that. Thanks @ravizombie .

**Comment by aj211082** [comment] 2016-07-26 03:08
I was having the same issue but solution is not to kill sshfs force fully or any hack around.

Just `umount <mounted dir>` and mount it again. I am using OS X 10.11.5

When I disconnect my mac from network, it always have problem to mount it again. I think better to put `mount` and `umount` commanda in your bash profile.

Another thing is your remote access would always be password protected and it fails to auto mount so you can try to login using your pre configured ssh keys.

**Comment by juj** [comment] 2017-04-07 12:04
Seeing this as well on OS X Sierra, after sshfs mount put laptop to sleep, and after reopening, the mount directory cannot be accessed with error `device not configured`. Attempting to sshfs mount again would give an error `mount_osxfuse: mount point /path/to/mount is itself on a OSXFUSE volume`. `sudo umount -f /path/to/mount` and then remounting works around the issue until next laptop sleep.

**Comment by lutaoact** [comment] 2017-05-12 05:48
This works for me every time.
```sh
ps aux | grep sshfs #get pid for sshfs
kill -9 pid #force to kill the process
sudo diskutil umount force mountpoint
```

**Comment by saurabhshri** [comment] 2017-07-02 15:34
@gtournie Two years later, still helpful! Thanks!

**Comment by paul-hammant** [comment] 2017-07-07 01:10
It is a shame the `Input/output error` message can't also say "consider killing rogue sshfs processes".

**Comment by SplitInf** [comment] 2017-11-23 16:12
`sudo diskutil unmount force /mount/path `
works for me consistently so far

**Comment by czypku** [comment] 2018-05-10 10:03
sudo diskutil umount force /path

works for me!

**Comment by nboaldin** [comment] 2018-07-04 19:42
still have to use 'diskutil unmount path/to/volume'

**Comment by eglxiang** [comment] 2018-10-01 18:28
Just reboot your computer and try the command again. Normally it works!

**Comment by ickc** [comment] 2018-10-01 18:31
> Just reboot your computer and try the command again. Normally it works!

See https://github.com/osxfuse/osxfuse/issues/45#issuecomment-21943107

**Comment by LBensman** [comment] 2019-09-27 16:04
I'm still having this issue, and none of the solutions above work.  I did notice some commonality of behavior when this happens, and hope that it helps.

My setup is 4 mount points (1 being used the most and I always notice the issue on it, but that's likely simply due to usage pattern).  All mount points are only accessible when VPN is running.  The most used mount point is mostly used to edit files using Visual Studio Code (see below).

Many times (usually waking up computer or re-establishing VPN), sshfs doesn't automatically reconnect, and I can simply `diskutil unmount force` and then remount (I have a script to run through all 4 mounts every time I detect that mount is misbehaving).  But occasionally it does give `mount_osxfuse: mount point /path/to/mount is itself on a OSXFUSE volume` and at that point it becomes nightmare.

What I just noticed is that preceding that error, I notice behavior that VSCode attempts to save an edited in file (I have it configured to autosave on all changes as I edit), but what happens is that remote file's length is reset to 0, and then nothing is written.  It is at this point that I try to remount and get that OSXFUSE error mentioned above.  I _also_ noticed that at this point VSCode continues to work *except* that I cannot quit it - it just doesn't respond to quit command at all.  Today I then opened some local file (I tried edit the aforementioned remount script to add `|| umount -f` at the end of `diskutil umount force` command) and VSCode read it in, but as it tried to save my edits, i got 0 length on local file as well.  When I opened the same file with `nano` and pasted new contents in there, `nano` saved it just fine.

I then though I'd take a look at what's going on with file descriptors by running `lsof | less` and it has been running for 20 minutes without producing any output.  Hitting `^C` simply produces `:...skipping...` for every keystroke.

So I think that sshfs cause some particular file operation to get stuck, thus affecting only a subset of file io operations.  nano doesn't trigger it, but `lsof` and VSCode do, and once they do, I have no recourse but to reboot.  `disutil umount force` at this point says it fails to unmount, `umount -f` seems to unmount, remount just continues to have problems, killing `sshfs` processes and remounting doesn't help, `hdiutil eject -f` is same.  `lsof` still gets stuck, VSCode is still in stuppor.

MacOS 10.14.1
SSHFS version 2.10
OSXFUSE 3.8.3
FUSE library version: 2.9.7

**Comment by kwcooper** [comment] 2020-01-01 07:47
Same issue for me, with none of the suggested solutions seeming to work apart from just making a new directory to mount to. 

MacOS Catalina
FUSE 3.10.4
SSHFS 2.5.0

**Comment by shell362** [comment] 2020-01-06 14:16
Let me join your club, guys.

**Comment by martinosorb** [comment] 2020-03-16 15:41
`killall sshfs` was sufficient for me.

**Comment by dmitvitalii** [comment] 2020-08-04 14:51
Same issue:
macOS 10.15.6
SSHFS 2.10
OSXFUSE 3.11.0

Didn't work:
```
sudo umount -f mountpoint
sudo diskutil unmount mountpoint
```

[This solution helped](https://github.com/osxfuse/osxfuse/issues/45#issuecomment-21943107).

**Comment by lukeweller** [comment] 2020-11-02 20:38
I'm running into the same problem as of November of 2020.  Whenever sshfs breaks, I'm unable to kill it or restart it without rebooting.  In addition, it also blocks every process that attempts to access the affected directory (mount, umount, diskutil, hdiutil, find, ls, cd, etc.).  These blocked processes don't respond to ctrl-c, and I'm forced to open up a new shell and send a kill signal to stop them.

Specs:
macOS 11.0.1 Beta (20B5012d)
SSHFS version 2.10
OSXFUSE 3.11.2
FUSE library version: 2.9.7

None of the following solutions have worked for me:
```
umount [MOUNT-DIR]
umount -f [MOUNT-DIR]
kill -9 [SSHFS-PID]
killall -9 sshfs
diskutil unmount force [MOUNT-DIR]
hditutil eject -force [MOUNT-DIR]
sshfs [SERVER] [MOUNT-DIR] -o reconnect
```

Note: While it's possible this issue could be the result of me using a Beta version of macOS (11.0.1), the fact that so many other people are having the same issue makes me think the os itself isn't the problem.

**Comment by kwcooper** [comment] 2020-11-03 14:21
Interesting those didn't work for you. I use those commands so often I set
up aliases.

`alias fixFS="killall sshfs"`
`alias MTFX="umount -f ~/<mount directory>"`

Just to add another example of the problem on my 2019 MBP running 10.15.6

**Comment by lukeweller** [comment] 2020-11-03 19:44
@kwcooper Thanks for taking the time to respond.

Would you be able to share the output of `ps aux | grep sshfs` and `ps aux | grep mount` on your system right before you call those two aliased commands?  I think it might be possible that my specific issues are my own doing, and not the fault of sshfs (at least not entirely).

For reference, my output when running those commands is currently: 
```
$ ps aux | grep sshfs
luke             12100   0.0  0.0  4268440    704 s002  R+    2:28PM   0:00.00 grep sshfs
luke             12092   0.0  0.0  4281932   1868   ??  U     2:28PM   0:00.01 sshfs [REMOTE_SERVER] /Users/Luke/mnt/cse

$ ps aux | grep mount
luke              1924   0.0  0.0  4384116   6412   ??  S     3:41PM   0:00.07 /System/Library/PrivateFrameworks/KerberosHelper/Helpers/DiskUnmountWatcher
luke             12116   0.0  0.0  4268440    712 s002  S+    2:30PM   0:00.00 grep mount
luke             12068   0.0  0.0  4279840    852   ??  U     2:26PM   0:00.00 mount
luke             12063   0.0  0.0  4382128   3636   ??  U     2:26PM   0:00.01 /Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse -o fsname=[REMOTE_SERVER],auto_cache /Users/luke/mnt/cse
```

**Comment by Flynamic** [comment] 2021-01-04 19:34
Same problem here, nothing in this thread worked so far except rebooting. This basically means that I have to unmount the folder before the connection is cut, or otherwise every process interacting with this folder in any way will freeze, including Finder – which will immediately exit everytime I try to restart it.

**Comment by dnicolson** [comment] 2021-04-18 00:09
This issue does not appear to be specific to sshfs. When using [ifuse](https://github.com/libimobiledevice/ifuse) if a device is disconnected the `ifuse` process needs to be killed and the path unmounted to resolve the issue.

**Comment by jhihn** [comment] 2021-04-18 05:27
That might be true, but that's not how it presents to the user. Back when I found this issue, because I was having it, I had no idea about the inner workings, despite mounting fss for years. 

As for how this applies to sshfs, can it detect that is the unmount fails, it at least has a force option that does what you describe?

**Comment by trankov** [comment] 2021-06-01 11:05
```sh
mount | grep @
```
All chars before `on /path/to/mount/folder` is the volume name. It looks like `name@server:/path`. Copy them. Then
```
sudo umount -f name@server:/path
```
If it doesn't helps, any other methods are useless, because `umount -f` is hardest way possible. Type `reboot`.

**Comment by AbeKh** [comment] 2021-11-27 19:23
I was running into this issue; `pgrep` approach was able to quick fix. As others have pointed out, this could be a ssh server timeout issue. I was able to reproduce the issue when using `-o reconnect` without any `ServerAlive` inputs. After server timeout, which is 8 hours on my server, this issue is presented. 

[This post at serverault](https://serverfault.com/a/639735) explained what I was facing, which might be related to the issue presented here.

**Comment by benlieb** [comment] 2021-12-07 00:29
Same issues. At first I tried `sudo diskutil umount force relative/mount/path`. This didn't work. But `sudo diskutil umount force /full/mount/path` worked.

**Comment by danijar** [comment] 2022-01-24 03:31
When my MacBook has sshfs running and goes to sleep for too long, after resume all internet connections will time out (e.g. when trying to access websites in the browser or even just `ping google.com` on the command line).

The following works for me (running the same command twice):

```
sudo killall sshfs -9
sudo killall sshfs -9
```

**Comment by bfleischer** [comment] 2024-11-30 01:03
A new SSHFS build is available on https://macfuse.io. Therefore, I'm closing this issue.

**Closed by bfleischer** 2024-11-30 01:03 UTC

**Comment by JuiceB0xC0de** [comment] 2025-10-15 19:02
Hi everyone! 👋

I came across this old thread while researching network connectivity issues with virtual machines and remote file systems. Even though this issue dates back to 2012, I thought I'd share a tool that might help anyone still dealing with similar connectivity debugging challenges.

We recently developed a network diagnostics tool with Wireshark capture functionality specifically for troubleshooting virtual machine and remote connection issues: https://github.com/JuiceB0xC0de/Liliths-Glitch

The repository includes:
- Automated packet capture functionality for diagnosing network disruptions
- Real-world Wireshark capture examples in the `/wireshark_captures` directory
- Tools for analyzing connection failures (like SSH tunnel drops, mount point issues, etc.)

This can be particularly useful for:
- Debugging SSHFS/network file system disconnections after sleep/wake cycles
- Analyzing why remote volumes become unmountable
- Identifying network-level issues that cause I/O errors on mounted volumes
- Understanding packet-level behavior during connection interruptions

The Wireshark captures can help identify whether issues are at the network layer, SSH layer, or FUSE layer - which has been a longstanding question in this thread.

Hope this helps anyone still debugging these frustrating connectivity problems! 🔧
